//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace joyeriaSYS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF_DETALLE_FACTURA
    {
        public int idDetalleFactura { get; set; }
        public int idFactura { get; set; }
        public int idProducto { get; set; }
        public int CantidadProducto { get; set; }
        public Nullable<int> CantidadDevuelta { get; set; }
    
        public virtual FAC_FACTURA FAC_FACTURA { get; set; }
        public virtual PRO_PRODUCTO PRO_PRODUCTO { get; set; }
    }
}
