//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace joyeriaSYS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAC_FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAC_FACTURA()
        {
            this.DEF_DETALLE_FACTURA = new HashSet<DEF_DETALLE_FACTURA>();
        }
    
        public int idFactura { get; set; }
        public int NoFactura { get; set; }
        public string CodTabla { get; set; }
        public decimal montoFactura { get; set; }
        public decimal saldo { get; set; }
        public decimal totalDevuelto { get; set; }
        public bool estado { get; set; }
        public int totalPiezas { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaLiquidacion { get; set; }
        public int idCliente { get; set; }
        public int idUsuario { get; set; }
        public int idCategoriaMetal { get; set; }
    
        public virtual CLI_CLIENTES CLI_CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEF_DETALLE_FACTURA> DEF_DETALLE_FACTURA { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
