//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace joyeriaSYS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JoyeriaEntities : DbContext
    {
        public JoyeriaEntities()
            : base("name=JoyeriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CAT_CATEGORIA> CAT_CATEGORIA { get; set; }
        public virtual DbSet<CLI_CLIENTES> CLI_CLIENTES { get; set; }
        public virtual DbSet<CQR_CODIGO_QR> CQR_CODIGO_QR { get; set; }
        public virtual DbSet<PRO_PRODUCTO> PRO_PRODUCTO { get; set; }
        public virtual DbSet<DEF_DETALLE_FACTURA> DEF_DETALLE_FACTURA { get; set; }
        public virtual DbSet<Vista_ProductosPorDetalleFactura> Vista_ProductosPorDetalleFactura { get; set; }
        public virtual DbSet<FAC_FACTURA> FAC_FACTURA { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SP_CantidadProductosEnLaFactura(Nullable<int> noFactura)
        {
            var noFacturaParameter = noFactura.HasValue ?
                new ObjectParameter("NoFactura", noFactura) :
                new ObjectParameter("NoFactura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CantidadProductosEnLaFactura", noFacturaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_SaldoDeFacturaCancelada(Nullable<int> noFactura)
        {
            var noFacturaParameter = noFactura.HasValue ?
                new ObjectParameter("NoFactura", noFactura) :
                new ObjectParameter("NoFactura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_SaldoDeFacturaCancelada", noFacturaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_SaldoDeFacturaNOCancelada(Nullable<int> noFactura)
        {
            var noFacturaParameter = noFactura.HasValue ?
                new ObjectParameter("NoFactura", noFactura) :
                new ObjectParameter("NoFactura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_SaldoDeFacturaNOCancelada", noFacturaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_SaldoDeFacturaCanceladaSINActualizarLaFacturaAun(Nullable<int> noFactura)
        {
            var noFacturaParameter = noFactura.HasValue ?
                new ObjectParameter("NoFactura", noFactura) :
                new ObjectParameter("NoFactura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_SaldoDeFacturaCanceladaSINActualizarLaFacturaAun", noFacturaParameter);
        }
    }
}
